#!/usr/bin/env python3
"""make_crystal.py — generate a small oriented bcc single crystal.

Writes a LAMMPS data file (readable by all LEGO-TOOLS binaries) with a
bcc crystal whose box axes point along given crystallographic directions.
Standard library only.

Usage:
  make_crystal.py --a0=3.1652 --x=1,1,1 --y=-1,0,1 --z=1,-2,1 \
                  --size=40,40,10 --mass=183.84 --out=W_edge_box.data \
                  [--center] [--shift=dx,dy,dz]

  --a0      lattice parameter (Angstrom)
  --x/y/z   crystallographic directions of the box axes (integers; must be
            mutually orthogonal and right-handed)
  --size    box lengths along x,y,z (Angstrom); the generated crystal fills
            [0,Lx)x[0,Ly)x[0,Lz)
  --center  put the origin at the box center (atoms in [-L/2, L/2))
  --shift   extra shift added to all atom coordinates (after --center)
  --mass    atomic mass for the Masses section (default 183.84, tungsten)
  --out     output file name

License: GPL-3.0
Author:  Erik Bitzek <e.bitzek@mpi-susmat.de>
         Max-Planck-Institut fuer Nachhaltige Materialien, Duesseldorf
Funding: NFDI-MatWerk
"""

import math
import sys


def parse_vec(s, n=3, typ=float):
    parts = [typ(t) for t in s.split(",")]
    if len(parts) != n:
        raise ValueError(f"expected {n} comma-separated values, got '{s}'")
    return parts


def normalized(v):
    s = math.sqrt(sum(c * c for c in v))
    return [c / s for c in v]


def dot(a, b):
    return sum(x * y for x, y in zip(a, b))


def cross(a, b):
    return [a[1] * b[2] - a[2] * b[1],
            a[2] * b[0] - a[0] * b[2],
            a[0] * b[1] - a[1] * b[0]]


def make_bcc(a0, ex, ey, ez, size, eps=1e-6):
    """Yield bcc atom positions (box coordinates, Angstrom) inside
    [0,Lx) x [0,Ly) x [0,Lz)."""
    lx, ly, lz = size
    # Bounding sphere of the box, in units of a0, around the box center.
    cx, cy, cz = lx / 2, ly / 2, lz / 2
    rad = math.sqrt(cx * cx + cy * cy + cz * cz) / a0 + 2.0
    # Box center in crystal coordinates (units of a0).
    cc = [(ex[i] * cx + ey[i] * cy + ez[i] * cz) / a0 for i in range(3)]
    n0 = [int(math.floor(c - rad)) for c in cc]
    n1 = [int(math.ceil(c + rad)) for c in cc]
    basis = [(0.0, 0.0, 0.0), (0.5, 0.5, 0.5)]
    for i in range(n0[0], n1[0] + 1):
        for j in range(n0[1], n1[1] + 1):
            for k in range(n0[2], n1[2] + 1):
                for bx, by, bz in basis:
                    # crystal coords (Angstrom)
                    px = (i + bx) * a0
                    py = (j + by) * a0
                    pz = (k + bz) * a0
                    # box coords
                    x = ex[0] * px + ex[1] * py + ex[2] * pz
                    y = ey[0] * px + ey[1] * py + ey[2] * pz
                    z = ez[0] * px + ez[1] * py + ez[2] * pz
                    if (-eps <= x < lx - eps and
                            -eps <= y < ly - eps and
                            -eps <= z < lz - eps):
                        yield (x, y, z)


def main(argv):
    a0 = 3.1652
    dx = [1, 1, 1]
    dy = [-1, 0, 1]
    dz = [1, -2, 1]
    size = [40.0, 40.0, 10.0]
    mass = 183.84
    out = None
    center = False
    shift = [0.0, 0.0, 0.0]

    for a in argv[1:]:
        if a.startswith("--a0="):
            a0 = float(a[5:])
        elif a.startswith("--x="):
            dx = parse_vec(a[4:])
        elif a.startswith("--y="):
            dy = parse_vec(a[4:])
        elif a.startswith("--z="):
            dz = parse_vec(a[4:])
        elif a.startswith("--size="):
            size = parse_vec(a[7:])
        elif a.startswith("--mass="):
            mass = float(a[7:])
        elif a.startswith("--out="):
            out = a[6:]
        elif a == "--center":
            center = True
        elif a.startswith("--shift="):
            shift = parse_vec(a[8:])
        else:
            sys.exit(f"make_crystal.py: unknown argument '{a}'\n\n{__doc__}")

    if out is None:
        sys.exit("make_crystal.py: --out=FILE is required")

    ex, ey, ez = normalized(dx), normalized(dy), normalized(dz)
    if (abs(dot(ex, ey)) > 1e-8 or abs(dot(ex, ez)) > 1e-8
            or abs(dot(ey, ez)) > 1e-8):
        sys.exit("make_crystal.py: box axes are not orthogonal")
    cz = cross(ex, ey)
    if any(abs(cz[i] - ez[i]) > 1e-8 for i in range(3)):
        sys.exit("make_crystal.py: box axes are not right-handed (z != x*y)")

    off = [shift[i] - (size[i] / 2 if center else 0.0) for i in range(3)]
    atoms = [(x + off[0], y + off[1], z + off[2])
             for x, y, z in make_bcc(a0, ex, ey, ez, size)]

    lo = off
    hi = [off[i] + size[i] for i in range(3)]
    with open(out, "w") as f:
        f.write(f"bcc crystal a0={a0} x={dx} y={dy} z={dz} "
                "(generated by make_crystal.py)\n\n")
        f.write(f"{len(atoms)} atoms\n1 atom types\n\n")
        f.write(f"{lo[0]:.10g} {hi[0]:.10g} xlo xhi\n")
        f.write(f"{lo[1]:.10g} {hi[1]:.10g} ylo yhi\n")
        f.write(f"{lo[2]:.10g} {hi[2]:.10g} zlo zhi\n\n")
        f.write(f"Masses\n\n1 {mass}\n\n")
        f.write("Atoms # atomic\n\n")
        for i, (x, y, z) in enumerate(atoms, 1):
            f.write(f"{i} 1 {x:.12f} {y:.12f} {z:.12f}\n")
    print(f"make_crystal.py: wrote {len(atoms)} atoms to {out}")


if __name__ == "__main__":
    main(sys.argv)
